[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fuzzbench"
version = "0.1.0"
dependencies = [
    "rapidfuzz==3.14.0",
    "psutil==5.9.8",
]

[tool.setuptools.packages.find]
where = ["src"]